-- Products: INTEGER → DECIMAL(12,4)
ALTER TABLE products ALTER COLUMN stock TYPE DECIMAL(12,4);
ALTER TABLE products ALTER COLUMN stock_available TYPE DECIMAL(12,4);
ALTER TABLE products ALTER COLUMN stock_blocked TYPE DECIMAL(12,4);

-- Bundles: INTEGER → DECIMAL(12,4)
ALTER TABLE bundles ALTER COLUMN stock TYPE DECIMAL(12,4);
ALTER TABLE bundles ALTER COLUMN stock_available TYPE DECIMAL(12,4);
ALTER TABLE bundles ALTER COLUMN stock_blocked TYPE DECIMAL(12,4);
