-- Revert to INTEGER
ALTER TABLE products ALTER COLUMN stock TYPE INTEGER;
ALTER TABLE products ALTER COLUMN stock_available TYPE INTEGER;
ALTER TABLE products ALTER COLUMN stock_blocked TYPE INTEGER;

ALTER TABLE bundles ALTER COLUMN stock TYPE INTEGER;
ALTER TABLE bundles ALTER COLUMN stock_available TYPE INTEGER;
ALTER TABLE bundles ALTER COLUMN stock_blocked TYPE INTEGER;
